// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUQR1LFml_C9sfsPer1sCPY6ShA1eJhC4',
    appId: '1:518485348258:web:ef58ac5981c7dd73332cfb',
    messagingSenderId: '518485348258',
    projectId: 'welltrack-de646',
    authDomain: 'welltrack-de646.firebaseapp.com',
    storageBucket: 'welltrack-de646.firebasestorage.app',
    measurementId: 'G-TYYDVD5YPY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2dRBls8uDZTjom3OsDTcouUD3nVhV8-A',
    appId: '1:518485348258:android:498ee5adc6182891332cfb',
    messagingSenderId: '518485348258',
    projectId: 'welltrack-de646',
    storageBucket: 'welltrack-de646.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUhU8HQMBNydl34-JzzJzfRkDIOPLV_uk',
    appId: '1:518485348258:ios:9b530e9a2a4ac428332cfb',
    messagingSenderId: '518485348258',
    projectId: 'welltrack-de646',
    storageBucket: 'welltrack-de646.firebasestorage.app',
    iosBundleId: 'com.example.welltrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUhU8HQMBNydl34-JzzJzfRkDIOPLV_uk',
    appId: '1:518485348258:ios:9b530e9a2a4ac428332cfb',
    messagingSenderId: '518485348258',
    projectId: 'welltrack-de646',
    storageBucket: 'welltrack-de646.firebasestorage.app',
    iosBundleId: 'com.example.welltrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUQR1LFml_C9sfsPer1sCPY6ShA1eJhC4',
    appId: '1:518485348258:web:42127d87bacfe0af332cfb',
    messagingSenderId: '518485348258',
    projectId: 'welltrack-de646',
    authDomain: 'welltrack-de646.firebaseapp.com',
    storageBucket: 'welltrack-de646.firebasestorage.app',
    measurementId: 'G-BFRQ01H250',
  );
}
